### ISSUE TITLE
Adding option='responsive' to table_header + getting default OS font

### ISSUE THREAD

**Issue by ClimenteA** [matiasrebori/fpdf-table#34]
Hi,

Thank you for creating this package, it's very useful!

I noticed that on table_header function option='responsive' is not available and longer text is not visibile.

Also, I'm wondering if is better to add default OS font for the class since the current default 'Helvetica' doesn't support diacritics.

**Comment by ClimenteA** [comment]
It looks like rows are not aligned as well.. 

![image](https://github.com/user-attachments/assets/973905d7-0f87-488a-9f90-7f5ca5a3ded5)

**Comment by matiasrebori** [comment]
Hi @ClimenteA, thanks for using my package.

Can you provide a template code so i can see the errors and try to fix them.

About the font, it is better if you add a custom font that supports your target language, for example to support unicode characters, check the function `add_fonts_custom `

**Comment by ClimenteA** [comment]
Here I have the sample code: https://github.com/ClimenteA/PFASimplu/blob/main/facturi%2Fmodels.py

**Comment by matiasrebori** [comment]
can you provide a live example of your use case, like this
![image](https://github.com/user-attachments/assets/f67ddd3e-9912-4224-8c6f-f13c7f97bcf9)
in order for me to test it

**Comment by ClimenteA** [comment]
The sample in your screenshoot should work - make the text in the header longer,  add more columns and you'll get the same result (text column is not visible and table coresponding cells are not under the right columns - see screenshot from my previous comments).

**Comment by matiasrebori** [comment]
So, currently there is no feature to make `table_header` responsive cause of the fill option, the result of trying to make table_row responsive is this
![image](https://github.com/user-attachments/assets/3f3a22b7-8d92-4286-a659-c3f8a3cf90d0)

Now, what you can do is the following:
1- define a fixed width for your table (you want horizontal limits to be fixed and vertical limits variable), you can use `table_cols`  to calculate the limits in a similar way to bootstrap
2- use `table_row` as a table header by changing the style

![image](https://github.com/user-attachments/assets/d2ff12b1-f37f-484c-b0a2-c1e7e7d95810)

this is the result of the above code
![image](https://github.com/user-attachments/assets/d9010398-1491-4e3f-a7e4-b351873d972a)

**Comment by ClimenteA** [comment]
Nice! Thank you!

This is good enough for me.
